name: "EK Aligo"
description: "Action for checking Golang struct alignment"
author: "ESSENTIALKAOS"

branding:
  icon: 'align-left'
  color: 'white'

inputs:
  files:
    description: "Files or directories to check"
    required: true

  path:
    description: "Path to directory with sources"
    required: false

  version:
    description: "Version of Aligo"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - id: aligo-install
      name: Install Aligo
      shell: bash
      run: |
        # [aligo-install]

        echo -e "::group::\033[34mBuilding Aligo…\033[0m"

        go install github.com/essentialkaos/aligo@v${{inputs.version}}

        mkdir -p ~/.cache
        cp "$(which aligo)" ~/.cache/aligo

        echo "::endgroup::"

    - id: aligo-version-print
      name: Print Aligo version info
      shell: bash
      run: |
        # [aligo-version-print]

        echo -e "::group::\033[34mPrint Aligo version…\033[0m"
        ~/.cache/aligo --version
        echo "::endgroup::"

    - id: aligo-check
      name: Check Golang sources with Aligo
      shell: bash
      run: |
        # [aligo-check]

        echo -e "\033[34mRunning Aligo…\033[0m"

        if [[ -n "${{inputs.path}}" ]] ; then
          pushd ${{inputs.path}} &> /dev/null
          ~/.cache/aligo check ${{inputs.files}}
          popd &> /dev/null
        else
          ~/.cache/aligo check ${{inputs.files}}
        fi
