name: "EK Aligo"
description: "Action for checking Golang struct alignment"
author: "ESSENTIALKAOS"

branding:
  icon: 'align-left'
  color: 'white'

inputs:
  files:
    description: "Files or directories to check"
    required: true

  path:
    description: "Path to directory with sources"
    required: false

  tags:
    description: "Build tags"
    required: false

runs:
  using: "composite"
  steps:
    - id: aligo-validate-options
      name: Options validation
      shell: bash
      run: |
        # [aligo-validate-options]

        if [[ -n "${{inputs.path}}" && ! -d "${{inputs.path}}" ]] ; then
          echo "::error::Directory ${{inputs.path}} doesn't exist"
          exit 1
        fi

    - id: aligo-install
      name: Install Aligo
      shell: bash
      run: |
        # [aligo-install]

        echo -e "::group::\033[34mBuilding Aligo…\033[0m"

        if ! go install github.com/essentialkaos/aligo@$latest ; then
          echo "::endgroup::"
          echo "::error::Can't install the latest version of aligo"
          exit 1
        fi

        mkdir -p ~/.bin
        cp "$(which aligo)" ~/.bin/aligo

        echo "::endgroup::"

    - id: aligo-version-print
      name: Print Aligo version info
      shell: bash
      run: |
        # [aligo-version-print]

        echo -e "::group::\033[34mPrint Aligo version info…\033[0m"
        ~/.bin/aligo --version
        echo "::endgroup::"

    - id: aligo-check
      name: Check Golang sources with Aligo
      shell: bash
      run: |
        # [aligo-check]

        echo -e "\033[34mRunning Aligo…\033[0m"

        if [[ -n "${{inputs.path}}" ]] ; then
          cd ${{inputs.path}}
        fi

        if [[ -n "${{inputs.tags}}" ]] ; then
          ~/.bin/aligo --tags "$tags" check ${{inputs.files}}
        else
          ~/.bin/aligo check ${{inputs.files}}
        fi
